name: Meme Bot

on:
  schedule:
    - cron: "0 12 * * *"
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  scrape-memes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y tesseract-ocr
          pip install praw tweepy requests pillow pytesseract python-dotenv
      
      - name: Scrape & Verify Memes
        run: python scrape_memes.py

      - name: Commit Memes for Review
        run: |
          git add memes_for_review.json
          git commit -m "Updated memes for review" || echo "No changes to commit"
          git push origin main

  post-meme:
    runs-on: ubuntu-latest
    needs: scrape-memes
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Post Meme
        run: python post_meme.py
